/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"context"
	"crypto/tls"
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"
	"sync"

	// Import all Kubernetes client auth plugins (e.g. Azure, GCP, OIDC, etc.)
	// to ensure that exec-entrypoint and run can make use of them.
	k8sresource "k8s.io/apimachinery/pkg/api/resource"
	corev1 "k8s.io/api/core/v1"
	resource "k8s.io/api/resource/v1beta1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	_ "k8s.io/client-go/plugin/pkg/client/auth"
	"k8s.io/utils/ptr"

	"k8s.io/apimachinery/pkg/runtime"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/healthz"
	"sigs.k8s.io/controller-runtime/pkg/log/zap"
	"sigs.k8s.io/controller-runtime/pkg/metrics/filters"
	metricsserver "sigs.k8s.io/controller-runtime/pkg/metrics/server"
	"sigs.k8s.io/controller-runtime/pkg/webhook"

	"github.com/rishibathina/dra-controller/internal/util"
	"github.com/rishibathina/dra-controller/internal/controller"
	// +kubebuilder:scaffold:imports
)

var (
	scheme   = runtime.NewScheme()
	setupLog = ctrl.Log.WithName("setup")
)

const (
	ControllerDriverName         = "tpu.google.com"
	ClusterResourceSliceName     = "subslice-tpu-resources"
)

func init() {
	utilruntime.Must(clientgoscheme.AddToScheme(scheme))
	utilruntime.Must(resource.AddToScheme(scheme)) 
	// +kubebuilder:scaffold:scheme
}

func main() {
	var metricsAddr string
	var enableLeaderElection bool
	var probeAddr string
	var secureMetrics bool
	var enableHTTP2 bool
	var tlsOpts []func(*tls.Config)
	flag.StringVar(&metricsAddr, "metrics-bind-address", "0", "The address the metrics endpoint binds to. "+
		"Use :8443 for HTTPS or :8080 for HTTP, or leave as 0 to disable the metrics service.")
	flag.StringVar(&probeAddr, "health-probe-bind-address", ":8081", "The address the probe endpoint binds to.")
	flag.BoolVar(&enableLeaderElection, "leader-elect", false,
		"Enable leader election for controller manager. "+
			"Enabling this will ensure there is only one active controller manager.")
	flag.BoolVar(&secureMetrics, "metrics-secure", true,
		"If set, the metrics endpoint is served securely via HTTPS. Use --metrics-secure=false to use HTTP instead.")
	flag.BoolVar(&enableHTTP2, "enable-http2", false,
		"If set, HTTP/2 will be enabled for the metrics and webhook servers")
	opts := zap.Options{
		Development: true,
	}
	opts.BindFlags(flag.CommandLine)
	flag.Parse()

	ctrl.SetLogger(zap.New(zap.UseFlagOptions(&opts)))

	// if the enable-http2 flag is false (the default), http/2 should be disabled
	// due to its vulnerabilities. More specifically, disabling http/2 will
	// prevent from being vulnerable to the HTTP/2 Stream Cancellation and
	// Rapid Reset CVEs. For more information see:
	// - https://github.com/advisories/GHSA-qppj-fm5r-hxr3
	// - https://github.com/advisories/GHSA-4374-p667-p6c8
	disableHTTP2 := func(c *tls.Config) {
		setupLog.Info("disabling http/2")
		c.NextProtos = []string{"http/1.1"}
	}

	if !enableHTTP2 {
		tlsOpts = append(tlsOpts, disableHTTP2)
	}

	webhookServer := webhook.NewServer(webhook.Options{
		TLSOpts: tlsOpts,
	})

	// Metrics endpoint is enabled in 'config/default/kustomization.yaml'. The Metrics options configure the server.
	// More info:
	// - https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.19.0/pkg/metrics/server
	// - https://book.kubebuilder.io/reference/metrics.html
	metricsServerOptions := metricsserver.Options{
		BindAddress:   metricsAddr,
		SecureServing: secureMetrics,
		// TODO(user): TLSOpts is used to allow configuring the TLS config used for the server. If certificates are
		// not provided, self-signed certificates will be generated by default. This option is not recommended for
		// production environments as self-signed certificates do not offer the same level of trust and security
		// as certificates issued by a trusted Certificate Authority (CA). The primary risk is potentially allowing
		// unauthorized access to sensitive metrics data. Consider replacing with CertDir, CertName, and KeyName
		// to provide certificates, ensuring the server communicates using trusted and secure certificates.
		TLSOpts: tlsOpts,
	}

	if secureMetrics {
		// FilterProvider is used to protect the metrics endpoint with authn/authz.
		// These configurations ensure that only authorized users and service accounts
		// can access the metrics endpoint. The RBAC are configured in 'config/rbac/kustomization.yaml'. More info:
		// https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.19.0/pkg/metrics/filters#WithAuthenticationAndAuthorization
		metricsServerOptions.FilterProvider = filters.WithAuthenticationAndAuthorization
	}

	mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
		Scheme:                 scheme,
		Metrics:                metricsServerOptions,
		WebhookServer:          webhookServer,
		HealthProbeBindAddress: probeAddr,
		LeaderElection:         enableLeaderElection,
		LeaderElectionID:       "99950f89.dra.fr",
		// LeaderElectionReleaseOnCancel defines if the leader should step down voluntarily
		// when the Manager ends. This requires the binary to immediately end when the
		// Manager is stopped, otherwise, this setting is unsafe. Setting this significantly
		// speeds up voluntary leader transitions as the new leader don't have to wait
		// LeaseDuration time first.
		//
		// In the default scaffold provided, the program ends immediately after
		// the manager stops, so would be fine to enable this option. However,
		// if you are doing or is intended to do any operation such as perform cleanups
		// after the manager stops then its usage might be unsafe.
		// LeaderElectionReleaseOnCancel: true,
	})
	if err != nil {
		setupLog.Error(err, "unable to start manager")
		os.Exit(1)
	}

	setupLog.Info("Attempting to create initial Subslice ResourceSlice")
	initialTPUMap, errCreateInitialSlice := createInitialClusterResourceSlice(context.Background(), mgr.GetClient())
	if errCreateInitialSlice != nil {
		setupLog.Error(errCreateInitialSlice, "failed to create initial Subslice ResourceSlice, reconciler will attempt later")
	}
	
	if initialTPUMap == nil { 
		setupLog.Info("No initial devices found")
		initialTPUMap = &sync.Map{}
	}

	if err = (&controller.NodeReconciler{
		Client:      mgr.GetClient(),
		Scheme:      mgr.GetScheme(),
		TPUDevicesMap: initialTPUMap, 
	}).SetupWithManager(mgr); err != nil {
		setupLog.Error(err, "unable to create controller", "controller", "Node")
		os.Exit(1)
	}
	// +kubebuilder:scaffold:builder

	if err := mgr.AddHealthzCheck("healthz", healthz.Ping); err != nil {
		setupLog.Error(err, "unable to set up health check")
		os.Exit(1)
	}
	if err := mgr.AddReadyzCheck("readyz", healthz.Ping); err != nil {
		setupLog.Error(err, "unable to set up ready check")
		os.Exit(1)
	}

	setupLog.Info("starting manager")
	if err := mgr.Start(ctrl.SetupSignalHandler()); err != nil {
		setupLog.Error(err, "problem running manager")
		os.Exit(1)
	}
}

func createInitialClusterResourceSlice(ctx context.Context, k8sClient client.Client) (*sync.Map, error) {
	nodeList := &corev1.NodeList{}
	if err := k8sClient.List(ctx, nodeList); err != nil {
		return nil, fmt.Errorf("unable to list nodes for initial ResourceSlice creation: %w", err)
	}

	// map from label + hash to set of nodes
	// value is a sync map with key node name and sm bool as val
	aggregatedTPUDevices := &sync.Map{}
	deviceCount := 0
	for _, node := range nodeList.Items {
		for labelKey, labelValue := range node.Labels {
			if _, isSubsliceLabel := util.SubsliceTPULabelsSet[labelKey]; isSubsliceLabel {
				combinedKey := labelKey + ":" + labelValue
				if nodeSet, exists := aggregatedTPUDevices.Load(combinedKey); exists {
					if _, nodeExists := nodeSet.(*sync.Map).Load(node.Name); !nodeExists {
						nodeSet.Store(node.Name, true)
					} else {
						continue
					}
				} else {
					nodeSet = &sync.Map{}
					nodeSet.Store(node.Name, true)
					aggregatedTPUDevices.Store(combinedKey, nodeSet)
					deviceCount += 1
				}
			}
		}
	}

	// need to figure out what to do when node devices dont exist
	// if deviceCount == 0 {
		
	// }

	devicesForPool := []resource.Device{}
	countersForSharedCapacity := map[string]resource.Counter

	aggregatedTPUDevices.Range(func(key, value interface{}) bool {
		combinedKeyForNodeSelector := key.(string)
		parts := strings.SplitN(combinedKeyForNodeSelector, ":", 2)
		labelKeyForSelector := ""
		labelValueForSelector := ""
		if len(parts) == 2 {
			labelKeyForSelector = parts[0]
			labelValueForSelector = parts[1]
		}

		if labelKeyForSelector == "" || !util.SubsliceTPULabelsSet[labelKeyForSelector] {
			setupLog.Error(fmt.Errorf("invalid or unrecognized label key for NodeSelector: '%s' from combined key '%s'", labelKeyForSelector, combinedKeyForNodeSelector), "Skipping device entry for this key")
			return true 
		}

		nodesWithThisDeviceTypeMap := value.(*sync.Map)
		nodesWithThisDeviceTypeMap.Range(func(nodeNameKey, _ interface{}) bool {
			nodeName := nodeNameKey.(string)
			devicesForPool = append(devicesForPool, resource.Device{
				Name: nodeName,
				Basic: &resource.BasicDevice{
					NodeSelector: &corev1.NodeSelector{
						MatchLabels: map[string]string{
							labelKeyForSelector: labelValueForSelector,
						},
					},
				}
			})
			countersForSharedCapacity[nodeName] = resource.Counter{
				Value: k8sresource.NewQuantity(1, k8sresource.DecimalSI),
			}
			return true 
		})
		return true
	})

	subsliceResourceSlice := &resource.ResourceSlice{
		ObjectMeta: metav1.ObjectMeta{
			Name: ClusterResourceSliceName,
		},
		Spec: resource.ResourceSliceSpec{
			Pool: &resource.ResourcePool{
				Name: ClusterResourceSliceName,
				Generation: 1,
				ResourceSliceCount: 1,
			}
			Driver: ControllerDriverName,
			PerDeviceNodeSelection: ptr.To(true),
			SharedCounters: []resource.CounterSet{
				{
					Name: "slice-counter-set",
					Counters: countersForSharedCapacity,
				},
			}
			Devices: devicesForPool,
		}
	}
	if err := k8sClient.Create(ctx, subsliceResourceSlice, metav1.CreateOptions{}); err != nil {
		if apierrors.IsAlreadyExists(err) {
			return aggregatedTPUDevices, nil
		}
		return nil, fmt.Errorf("unable to create initial ResourceSlice: %w", err)
	}

	fmt.Printf("Successfully created ResourceSlice '%s'\n", subsliceResourceSlice.Name)

	return aggregatedTPUDevices, nil
}